apiVersion: apps/v1
kind: Deployment
metadata:
  name: adhan-backend
  namespace: adhan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adhan-backend
  template:
    metadata:
      labels:
        app: adhan-backend
    spec:
      containers:
      - name: backend
        image: youruser/adhan-api-backend:latest
        ports:
        - containerPort: 8000