apiVersion: v1
kind: Service
metadata:
  name: adhan-backend
  namespace: adhan
spec:
  type: ClusterIP
  selector:
    app: adhan-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: adhan-frontend
  namespace: adhan
spec:
  type: NodePort
  selector:
    app: adhan-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000   # accessible at http://<pi_ip>:32000