apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: "pihole/pihole:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: WEBPASSWORD
          value: {{ .Values.adminPassword | quote }}
        # Official v6 dynamic IP mapping
        - name: FTLCONF_dns_reply_host_IPv4
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}

        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-dnsmasq