apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: "pihole/pihole:latest"
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: WEBPASSWORD
          value: {{ .Values.adminPassword | quote }}
        # Map dynamic Host IP for v6
        - name: FTLCONF_dns_reply_host_IPv4
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-dnsmasq