apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      # SWITCHED TO FALSE so Ingress can manage the traffic
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: pihole
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # Re-adding internal ports so the Service/Ingress can find the container
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: dns-udp
            containerPort: 53
            protocol: UDP
          - name: dns-tcp
            containerPort: 53
            protocol: TCP
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: WEBPASSWORD
          value: {{ .Values.adminPassword | quote }}
        - name: VIRTUAL_HOST
          value: "pi.hole"
        - name: FTLCONF_webserver_api_allowedHosts
          value: "*"
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_NICE", "CHOWN"]
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-dnsmasq