apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: WEBPASSWORD
          value: {{ .Values.adminPassword | quote }}
        - name: VIRTUAL_HOST
          value: "pi.hole"
        
        # DYNAMIC IP OVERRIDE: Tells Pi-hole to use the Pi's IP for DNS
        - name: FTLCONF_dns_piholeAddress
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

        # Map variables from values.yaml
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}

        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-dnsmasq