apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pihole.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: pihole
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        # REMOVED the ports block to clear the 'Pending' port conflict
        env:
        - name: TZ
          value: {{ .Values.timezone | quote }}
        - name: WEBPASSWORD
          value: {{ .Values.adminPassword | quote }}
        - name: VIRTUAL_HOST
          value: "pi.hole"
        - name: FTLCONF_webserver_api_allowedHosts
          value: "*"
        - name: FTLCONF_webserver_servername
          value: "pi.hole"
        - name: FTLCONF_dns_override_pihole_address
          value: "192.168.1.42"
        - name: FTLCONF_webserver_api_trustedProxies
          value: "10.42.0.0/16,10.43.0.0/16,192.168.1.0/24"
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
        - name: dnsmasq-data
          mountPath: /etc/dnsmasq.d
        securityContext:
          privileged: true 
          capabilities:
            add: ["NET_ADMIN", "SYS_NICE", "CHOWN"]
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-data
      - name: dnsmasq-data
        persistentVolumeClaim:
          claimName: {{ include "pihole.fullname" . }}-dnsmasq