apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # This is the magic line for IP-based access
    nginx.ingress.kubernetes.io/default-backend: {{ include "pihole.fullname" . }}
    nginx.ingress.kubernetes.io/app-root: /admin
spec:
  ingressClassName: nginx
  # Adding this block allows the IP address to work
  defaultBackend:
    service:
      name: {{ include "pihole.fullname" . }}
      port:
        number: 80
  rules:
  - host: pi.hole
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "pihole.fullname" . }}
            port:
              number: 80