apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  namespace: {{ .Release.Namespace }}
  annotations:
    # Essential for MetalLB to use the same IP for TCP/UDP
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  type: LoadBalancer
  # Use your requested static IP here
#   loadBalancerIP: 192.168.1.42
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP