# templates/unbound-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
spec:
data:
  unbound.conf: |
    server:
      interface: 0.0.0.0
      port: {{ .Values.unbound.port }}
      verbosity: 1
      do-ip4: yes
      do-udp: yes
      do-tcp: yes
      do-ip6: no
      hide-identity: yes
      hide-version: yes
      harden-glue: yes
      harden-dnssec-stripped: yes
      prefetch: yes
      num-threads: 2